services:
  - type: web
    name: dlama-global-showcase
    env: node
    buildCommand: npm install && npm run build
    startCommand: node server-node.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
